// Code generated by sqlc. DO NOT EDIT.

package persist

import (
	"database/sql"
)

type Activity struct {
	ID  string
	CID sql.NullString
	Ts  sql.NullTime
}

type Catalog struct {
	ID          string
	Img         []byte
	Title       sql.NullString
	Description sql.NullString
}
