// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package persist

import (
	"context"
	"database/sql"
	"time"
)

const getAllUsage = `-- name: GetAllUsage :many
SELECT id, c_id, ts, note FROM ACTIVITY WHERE c_id=$1 ORDER BY ts DESC
`

func (q *Queries) GetAllUsage(ctx context.Context, cID string) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsage, cID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.CID,
			&i.Ts,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCatalog = `-- name: GetCatalog :one
SELECT id, category, brand, color, pattern, title, description, price, last_activity, last_note, hidden FROM CATALOG WHERE id=$1
`

func (q *Queries) GetCatalog(ctx context.Context, id string) (Catalog, error) {
	row := q.db.QueryRowContext(ctx, getCatalog, id)
	var i Catalog
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Brand,
		&i.Color,
		&i.Pattern,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.LastActivity,
		&i.LastNote,
		&i.Hidden,
	)
	return i, err
}

const getLastUsage = `-- name: GetLastUsage :one
SELECT id, c_id, ts, note FROM ACTIVITY WHERE c_id=$1 ORDER BY ts DESC LIMIT 1
`

func (q *Queries) GetLastUsage(ctx context.Context, cID string) (Activity, error) {
	row := q.db.QueryRowContext(ctx, getLastUsage, cID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CID,
		&i.Ts,
		&i.Note,
	)
	return i, err
}

const getUsage = `-- name: GetUsage :one
SELECT id, c_id, ts, note FROM ACTIVITY WHERE id=$1
`

func (q *Queries) GetUsage(ctx context.Context, id string) (Activity, error) {
	row := q.db.QueryRowContext(ctx, getUsage, id)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CID,
		&i.Ts,
		&i.Note,
	)
	return i, err
}

const listCatalog = `-- name: ListCatalog :many
SELECT id, category, brand, color, pattern, title, description, price, last_activity, last_note, hidden FROM CATALOG ORDER BY hidden ASC, last_activity DESC NULLS LAST
`

func (q *Queries) ListCatalog(ctx context.Context) ([]Catalog, error) {
	rows, err := q.db.QueryContext(ctx, listCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Catalog
	for rows.Next() {
		var i Catalog
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Brand,
			&i.Color,
			&i.Pattern,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.LastActivity,
			&i.LastNote,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsage = `-- name: ListUsage :many
SELECT id, c_id, ts, note FROM ACTIVITY ORDER BY ts DESC
`

func (q *Queries) ListUsage(ctx context.Context) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.CID,
			&i.Ts,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logUsage = `-- name: LogUsage :execresult
INSERT INTO ACTIVITY(id, c_id, ts) values ($1, $2, $3)
`

type LogUsageParams struct {
	ID  string
	CID string
	Ts  time.Time
}

func (q *Queries) LogUsage(ctx context.Context, arg LogUsageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, logUsage, arg.ID, arg.CID, arg.Ts)
}

const putItem = `-- name: PutItem :execresult
INSERT INTO catalog
(id, category, brand, color, pattern, title, description, price)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET category=$2, brand=$3, color=$4, pattern=$5, title=$6, description=$7, price=$8
`

type PutItemParams struct {
	ID          string
	Category    sql.NullString
	Brand       sql.NullString
	Color       sql.NullString
	Pattern     sql.NullString
	Title       sql.NullString
	Description sql.NullString
	Price       sql.NullFloat64
}

func (q *Queries) PutItem(ctx context.Context, arg PutItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, putItem,
		arg.ID,
		arg.Category,
		arg.Brand,
		arg.Color,
		arg.Pattern,
		arg.Title,
		arg.Description,
		arg.Price,
	)
}

const putUsage = `-- name: PutUsage :execresult
UPDATE activity SET note=$1, ts=$2 WHERE id=$3
`

type PutUsageParams struct {
	Note sql.NullString
	Ts   time.Time
	ID   string
}

func (q *Queries) PutUsage(ctx context.Context, arg PutUsageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, putUsage, arg.Note, arg.Ts, arg.ID)
}

const searchCatalog = `-- name: SearchCatalog :many
SELECT id, category, brand, color, pattern, title, description, price, last_activity, last_note, hidden FROM CATALOG WHERE LOWER(title) LIKE '%' || LOWER($1) || '%'
	OR LOWER(description) LIKE '%' || LOWER($1) || '%'
	OR LOWER(color) LIKE '%' || LOWER($1) || '%'
	OR LOWER(category) LIKE '%' || LOWER($1) || '%'
	OR LOWER(brand) LIKE '%' || LOWER($1) || '%'
	OR LOWER(pattern) LIKE '%' || LOWER($1) || '%'
	ORDER BY hidden ASC, last_activity DESC NULLS LAST
`

func (q *Queries) SearchCatalog(ctx context.Context, lower string) ([]Catalog, error) {
	rows, err := q.db.QueryContext(ctx, searchCatalog, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Catalog
	for rows.Next() {
		var i Catalog
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Brand,
			&i.Color,
			&i.Pattern,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.LastActivity,
			&i.LastNote,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHidden = `-- name: SetHidden :exec
UPDATE catalog SET hidden=$1 WHERE id=$2
`

type SetHiddenParams struct {
	Hidden bool
	ID     string
}

func (q *Queries) SetHidden(ctx context.Context, arg SetHiddenParams) error {
	_, err := q.db.ExecContext(ctx, setHidden, arg.Hidden, arg.ID)
	return err
}

const setUsageNote = `-- name: SetUsageNote :execresult
UPDATE activity SET note=$1 WHERE id=$2
`

type SetUsageNoteParams struct {
	Note sql.NullString
	ID   string
}

func (q *Queries) SetUsageNote(ctx context.Context, arg SetUsageNoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setUsageNote, arg.Note, arg.ID)
}

const updateLastNote = `-- name: UpdateLastNote :execresult
UPDATE catalog SET last_note=$1 WHERE id=$2
`

type UpdateLastNoteParams struct {
	LastNote sql.NullString
	ID       string
}

func (q *Queries) UpdateLastNote(ctx context.Context, arg UpdateLastNoteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateLastNote, arg.LastNote, arg.ID)
}

const updateLastUsed = `-- name: UpdateLastUsed :execresult
UPDATE catalog SET last_activity=$1, last_note=NULL WHERE id=$2
`

type UpdateLastUsedParams struct {
	LastActivity sql.NullTime
	ID           string
}

func (q *Queries) UpdateLastUsed(ctx context.Context, arg UpdateLastUsedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateLastUsed, arg.LastActivity, arg.ID)
}
